FS-928 Optimize bom cmd format according to thread discussion.
metal-toolbox/mctl pull request #49
Opened 2023-09-25 18:57 UTC by Alva8756

This PR optimized the bom cmd format according to discussion in slack thread https://equinix.slack.com/archives/C056JN319PG/p1695317935291199

example:
```
mctl % ./mctl create bom --from-xlsx-file ~/Downloads/test-alva1.xlsx
 &{0 0 0 0 0 {0x1400061a1f0 <nil> <nil> <nil> <nil>} resource created   <nil> <nil>}
mctl % ./mctl get bom --aoc-mac B5                                   
[
  {
    "serial_num": "A5",
    "aoc_mac_address": "B5,B6",
    "bmc_mac_address": "bmc1,bmc2",
    "num_defi_pmi": "3CECEFCF0087",
    "num_def_pwd": "FIWUZMZZGQ",
    "metro": ""
  }
]
mctl % ./mctl get bom --bmc-mac bmc1                                 
[
  {
    "serial_num": "A5",
    "aoc_mac_address": "B5,B6",
    "bmc_mac_address": "bmc1,bmc2",
    "num_defi_pmi": "3CECEFCF0087",
    "num_def_pwd": "FIWUZMZZGQ",
    "metro": ""
  }
]
```
error example:
```
mctl % ./mctl get bom                  
 --aoc-mac and --bmc-mac not set
mctl % ./mctl get bom --bmc-mac bmc1 --aoc-mac b1
 --aoc-mac and --bmc-mac should not set simutansly
```
Tested both locally and in sandbox.

2023-09-25 20:40 UTC, DoctorVin requested changes
Small change requested. Looks fine otherwise.

2023-09-25 20:40 UTC, DoctorVin commented on cmd/get/bom.go
> +			log.Fatalf("--aoc-mac and --bmc-mac should not set simutansly")
Spelling on `simultaneously`. Also, defer this to Cobra: https://pkg.go.dev/github.com/spf13/cobra#Command.MarkFlagsMutuallyExclusive

2023-09-25 21:36 UTC, DoctorVin requested changes
I know it's kind of a hassle, but if you could remove the test that will never come back true that would be best.

2023-09-25 21:36 UTC, DoctorVin commented on cmd/get/bom.go
>  		if flagsGetBomByMacAddress.hasAOCMacAddr() && flagsGetBomByMacAddress.hasBMCMacAddr() {
With cobra marking these as mutually exclusive, I don't think we'll ever get here. I think the library will terminate on an error.

2023-09-26 05:16 UTC, Alva8756 commented
> I know it's kind of a hassle, but if you could remove the test that will never come back true that would be best.

Thanks Vince,
I am lost here. Can you please help explain more about "remove the test"? I didn't add test to this PR.
Do you suggest I paste logs that's sending invalid requests and getting failures?

2023-09-26 11:12 UTC, DoctorVin commented
> > I know it's kind of a hassle, but if you could remove the test that will never come back true that would be best.
> 
> Thanks Vince, I am lost here. Can you please help explain more about "remove the test"? I didn't add test to this PR. Do you suggest I paste logs that's sending invalid requests and getting failures?

I meant “remove the if statement”. You got it.

2023-09-26 16:58 UTC, merged